# Generated by Django 6.0.2 on 2026-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chats_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
