# Generated by Django 6.0.2 on 2026-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_chats_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
