# Generated by Django 6.0.2 on 2026-02-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chats_creator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(default='Empty content')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['-created_datetime']},
        ),
    ]
