# Generated by Django 6.0.2 on 2026-02-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_alter_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='messenger.postcategory'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
