# Generated by Django 6.0.2 on 2026-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_remove_posts_category_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='messenger.postcategory'),
        ),
    ]
