# Generated by Django 6.0.2 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='purposed_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
