# Generated by Django 6.0.2 on 2026-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
