# Generated by Django 6.0.2 on 2026-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубиковано')], default=0),
        ),
    ]
